server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    root: warn

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler
  global-config:
    banner: false
    db-config:
      # 全局逻辑删除字段名
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

#jwt(token)配置
jwt:
  # 签名算法
  algorithm: HMAC
  #签名秘钥
  secretKey: drama@2024
  #过期时间(单位 hour)
  expirationTime: 3
  #设置前端传递过来的令牌名称,优先匹配Authorization。
  tokenName: drama_token
captcha:
  #验证码开关
  enable: true
  #过期时间(单位 minute)
  expire: 3
  #验证码类型
  type: math
  #验证码长度
  length: 4
  #验证码宽度
  width: 100
  #验证码高度
  height: 40

# springdoc-openapi项目配置
#springdoc:
#  swagger-ui:
#    path: /swagger-ui.html
#    tags-sorter: alpha
#    operations-sorter: alpha
#  api-docs:
#    path: /v3/api-docs
#  group-configs:
#    - group: 'default'
#      paths-to-match: '/**'
#      packages-to-scan: io.rainforest.banana.client1.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    # Basic认证用户名
    username: dramaDoc
    # Basic认证密码
    password: knife4jDoc@2024#4drama

---
spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/online_exam?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: root
logging:
  level:
    root: info
    sql: debug


